version: '3.8'

services:
  php-apache:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: rbs292003sep
      DB_NAME: note

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rbs292003sep
      MYSQL_DATABASE: note
    volumes:
      - mysql_data:/var/lib/mysql
      - ./note.sql:/docker-entrypoint-initdb.d/note.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mysql_data:
